<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Nefaur" failures="1" tests="1" name="Test" time="14.134" errors="0" timestamp="01 Nov 2018 20:42:47 GMT">
  <testcase classname="com.heatclinic.testngtests.LoginTests" name="validLogin" time="0.021">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.heatclinic.pages.HomePage.goToHomepage(HomePage.java:42)
at com.heatclinic.testngtests.LoginTests.validLogin(LoginTests.java:24)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- validLogin -->
</testsuite> <!-- Test -->
